# Generated by Django 2.2.5 on 2019-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('contact_type', models.CharField(choices=[('tel', 'Телефон (+380)'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('skype', 'Skype'), ('hangouts', 'Hangouts'), ('VK', 'VK(ссылка на профиль)'), ('email', 'E-mail')], default='tel', max_length=12, verbose_name='Тип связи')),
                ('contact_data', models.CharField(max_length=255, unique=True, verbose_name='Данные для контакта')),
            ],
        ),
    ]
