# Generated by Django 2.2.5 on 2019-09-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='contact_name',
        ),
    ]
