# Generated by Django 2.2.7 on 2019-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190928_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_type',
            field=models.CharField(choices=[('tel', 'Телефон (+38)'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('skype', 'Skype'), ('hangouts', 'Hangouts'), ('VK', 'VK(ссылка на профиль)'), ('email', 'E-mail')], default='tel', max_length=12, verbose_name='Тип связи'),
        ),
    ]
