# Generated by Django 2.2.5 on 2019-09-15 06:00

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок слайда')),
                ('description', models.CharField(max_length=255, verbose_name='Описание слайда')),
                ('image', models.ImageField(null=True, upload_to=shop.models.slider_image_file_path, verbose_name='Слайд')),
            ],
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название клиента')),
                ('image', models.ImageField(upload_to=shop.models.our_clients_image_file_path, verbose_name='Иконка компании')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
