# Generated by Django 2.2.5 on 2019-09-15 07:16

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_is_top_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterModelOptions(
            name='ourclients',
            options={'verbose_name': 'Наш клиент', 'verbose_name_plural': 'Нашы клиенты'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=shop.models.works_image_file_path, verbose_name='Фото работы')),
                ('large_img', models.BooleanField(default=False, verbose_name='Большая плитка')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Категория товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Реальный прототиа товра')),
            ],
            options={
                'verbose_name': 'Наша работа',
                'verbose_name_plural': 'Нашы работы',
            },
        ),
    ]
