# Generated by Django 2.2.5 on 2019-09-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190915_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourworks',
            name='category',
        ),
    ]
