# Generated by Django 2.2.5 on 2019-09-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_ourworks_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='imgs',
        ),
    ]
