# Generated by Django 2.2.5 on 2019-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190915_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgs',
            field=models.ManyToManyField(related_name='imgs', to='shop.Photo', verbose_name='Фото товара'),
        ),
    ]
