# Generated by Django 2.2.5 on 2019-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190928_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('brown', 'Коричневый(стандартный)'), ('red', 'Красный'), ('blue', 'Синий')], default='b', max_length=10, verbose_name='Тип связи'),
        ),
    ]
