# Generated by Django 2.2.5 on 2019-10-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(choices=[('accessory', 'Аксессуар'), ('bag', 'Сумка'), ('belt', 'Ремень'), ('cover', 'Обложка'), ('engraving', 'Гравировка'), ('housekeeper', 'Ключница'), ('portmone', 'Портмоне'), ('purse', 'Кошелек')], max_length=200),
        ),
    ]
