# Generated by Django 2.2.8 on 2019-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_soc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(choices=[('accessory', 'Аксессуар'), ('bag', 'Сумка'), ('belt', 'Ремень'), ('cover', 'Обложка'), ('housekeeper', 'Ключница'), ('portmone', 'Портмоне'), ('purse', 'Кошелек')], max_length=200),
        ),
        migrations.CreateModel(
            name='Engraving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Титл гравировки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('imgs', models.ManyToManyField(related_name='engraving_imgs', to='shop.Photo', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Гравировка',
                'verbose_name_plural': 'Гравировки',
                'ordering': ['title', '-created_date'],
            },
        ),
    ]
