# Generated by Django 2.2.8 on 2019-12-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20191215_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engraving',
            options={'ordering': ['title'], 'verbose_name': 'Гравировка', 'verbose_name_plural': 'Гравировки'},
        ),
        migrations.RemoveField(
            model_name='engraving',
            name='imgs',
        ),
        migrations.AddField(
            model_name='engraving',
            name='imgs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Photo', verbose_name='Фото товара'),
        ),
    ]
