# Generated by Django 2.2.9 on 2019-12-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20191222_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engraving',
            name='imgs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Photo', verbose_name='Фото товара'),
        ),
    ]
