# Generated by Django 2.2.9 on 2019-12-26 21:25

from django.db import migrations
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20191222_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=80, size=[1600, 900], upload_to=shop.models.product_image_file_path, verbose_name='Фото товара'),
        ),
    ]
