# Generated by Django 2.2.7 on 2019-12-26 22:57

from django.db import migrations
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20191226_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engraving',
            old_name='imgs',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=70, size=[1600, 900], upload_to=shop.models.product_image_file_path, verbose_name='Фото товара'),
        ),
    ]
