# Generated by Django 2.2.9 on 2019-12-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20191228_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
