# Generated by Django 2.2.9 on 2019-12-30 11:52

from django.db import migrations
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20191230_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=72, size=[800, 480], upload_to=shop.models.works_image_file_path, verbose_name='Фото товара'),
        ),
    ]
