# Generated by Django 2.2.9 on 2019-12-30 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20191230_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engraving',
            options={'ordering': ['-created_date'], 'verbose_name': 'Гравировка', 'verbose_name_plural': 'Гравировки'},
        ),
        migrations.RemoveField(
            model_name='engraving',
            name='available',
        ),
        migrations.RemoveField(
            model_name='engraving',
            name='price',
        ),
        migrations.RemoveField(
            model_name='engraving',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
