# Generated by Django 2.2.5 on 2019-09-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
