# Generated by Django 2.2.5 on 2019-10-07 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190928_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор ордера', primary_key=True, serialize=False),
        ),
    ]
