# Generated by Django 2.2.7 on 2019-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190928_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В работе'), ('done', 'Выполнен'), ('cancel', 'Отменен')], default='pending', max_length=255, verbose_name='Статус выполнения ордера'),
        ),
    ]
