# Generated by Django 2.2.7 on 2019-11-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191130_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='close_date',
            new_name='due_date',
        ),
    ]
